# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Jekyll Disqus Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: SuperJuara forum

# Your name, as you want it to appear underneath each post and in the footer
author: Firdaus siregar

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://superjuara.github.com/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: superjuaraforum

# The public key for your disqus application
disqus_publickey: cVy9WcjLl6TI8EbBAL6PDy8FqMr4gm3HXXfERv7anOYHj3AZAyO2jD66Pqqe71B0
